import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  header: {
    backgroundColor: '#D9D9D9',
  },
  headerTitle: {
    fontWeight: 'bold',
    fontFamily: 'Trebuchet',
    marginLeft: 20,
    color: ' #c64c38',
  },
  logo: {
    width: 100,
    height: 50,
    margin: 15,
  },
  mainContainer: {
    backgroundColor: '#D9D9D9',
    fontFamily: 'Trebuchet',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  container: {
    backgroundColor: '#ffffff',
    fontFamily: 'Trebuchet',
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 22,
    marginBottom: 5,
    marginHorizontal: 5,
    textAlign: 'center',
    fontFamily: 'Trebuchet',
    fontWeight: 'bold',
  },
  contactItem: {
    flex: 1,
    alignItems: 'flex-start',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#D9D9D9',
  },
  contactField: {
    fontFamily: 'Trebuchet',
    fontSize: 16,
    color: '#941a1d',
  },
  contactText: {
    fontSize: 16,
    fontFamily: 'Trebuchet',
    color: '#262626',
    textAlign: 'left',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  button: {
    margin: 14,
    width: 250,
    height: 50,
    backgroundColor: '#cb6d4f',
    padding: 15,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: '#ffffff',
    fontFamily: 'Trebuchet',
    fontSize: 18,
    textAlign: 'center',
  },
  actionButton: {
    margin: 7,
    width: '45%',
    height: 40,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 10,
    justifyContent: 'center',
    backgroundColor: '#941a1d',
  },
  actionText: {
    color: '#ffffff',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Trebuchet',
  },
  input: {
    height: 40,
    width: '90%',
    borderColor: '#595959',
    color: '#262626',
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 10,
    fontFamily: 'Trebuchet',
  },
  settingItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#D9D9D9',
  },
  settingText: {
    fontSize: 16,
    fontFamily: 'Trebuchet',
    color: '#941a1d',
    textAlign: 'left',
  },
  icon: {
    width: 200,
    height: 50,
    resizeMode: 'contain',
    marginRight: 10,
  },
  imageContainer: {
    flexDirection: 'row',
    margin: 20,
  },
  image: {
    width: 250,
    height: 200,
  },
});
